services:
  servarr-webhooks:
    image: ghcr.io/your-user/servarr-webhooks:latest
    container_name: servarr-webhooks
    restart: unless-stopped
    ports:
      - 5001:5001
    shm_size: 4gb
    stop_grace_period: 60s
    environment:
      - TZ=${{ tz }}
      - SEERR_BASEURL=http://192.168.1.67:5055
      - SEERR_API_KEY=
      - RADARR_BASEURL=http://192.168.1.67:7878
      - RADARR_API_KEY=
      - SONARR_BASEURL=http://192.168.1.67:8989
      - SONARR_API_KEY=
      - SONARR_TARGET_QUALITY_PROFILE_ID=16
      - ROOT_FOLDER_ANIME_MOVIES=/cache/anime_movies
      - TRANSCODE_WORKERS=2
      - TRANSCODE_TEMP_FALLBACK=/config/transcode-temp
    volumes:
      - ${{ sf:"appdata" }}/servarr-webhooks:/config
      - ${{ sf:"media" }}:/media:shared
      - ${{ sf:"cache" }}:/cache:shared
    devices:
      - /dev/dri:/dev/dri
    cpu_shares: 512
