services:
  servarr-webhooks:
    image: ghcr.io/cmaguranis/servarr-webhooks:latest
    container_name: servarr-webhooks
    restart: unless-stopped
    ports:
      - 5001:5001
    shm_size: 4gb
    stop_grace_period: 20s
    environment:
      - TZ=${{ tz }}
      - PLEX_BASEURL=http://192.168.1.67:32400
      - PLEX_TOKEN=
      - SEERR_BASEURL=http://192.168.1.67:5055
      - RADARR_BASEURL=http://192.168.1.67:7878
      - SONARR_BASEURL=http://192.168.1.67:8989
      - SEERR_API_KEY=
      - RADARR_API_KEY=
      - SONARR_API_KEY=
      - SONARR_TARGET_QUALITY_PROFILE_ID=23
      - SEERR_ROOT_FOLDER_ANIME_MOVIES=/data/media_cache/anime_movies
      - TRANSCODE_WORKER_COUNT=2
      - TRANSCODE_TEMP_FALLBACK=/config/transcode-temp
      - TEST_MEDIA_WORKER_COUNT=1
      - TEST_MEDIA_OUTPUT_DIR=/data/media_test
      - TEST_MEDIA_MEDIA_DIR=/media
    volumes:
      - ${{ sf:"appdata" }}/servarr-webhooks:/config
      - ${{ sf:"media" }}:/media:shared
      - ${{ sf:"cache" }}:/data:rshared
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "7"
    cpu_shares: 512