FROM python:3

ENV SEERR_BASEURL ''
ENV SEERR_API_KEY ''
ENV RADARR_BASEURL ''
ENV RADARR_API_KEY ''
ENV SONARR_BASEURL ''
ENV SONARR_API_KEY ''
ENV SONARR_TARGET_QUALITY_PROFILE_ID ''
ENV ROOT_FOLDER_ANIME_MOVIES ''

ADD requirements.txt /

RUN pip install -r requirements.txt

ADD main.py /

CMD [ "python", "./main.py" ] 
